GET /product{?category,priceFrom,priceTo}
< 200
< Accept: application/json
GET /product/{id}
< 200
< Accept: application/json
DELETE /product/{id}
< 200
< Accept: application/json
GET /order/{id}
< 200
< Accept: application/json